# Generated by Django 5.0.6 on 2024-09-16 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='create',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
