# Generated by Django 5.0.6 on 2024-09-17 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_create_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='create',
            name='user',
            field=models.CharField(max_length=100),
        ),
    ]
