# Generated by Django 5.0.6 on 2024-09-20 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_contact_remove_create_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='create',
            name='due_date',
            field=models.DateTimeField(),
        ),
    ]
